# Generated by Django 4.2 on 2023-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
