# Generated by Django 4.2 on 2023-10-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_payment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_name',
        ),
    ]
