# Generated by Django 4.2 on 2023-10-29 17:32

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_payment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('items', models.JSONField()),
                ('customer', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'completed')], default=0)),
                ('payment_method', models.IntegerField(choices=[(1, 'strip'), (2, 'paypal')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=courses.models.Course, to='courses.transaction'),
        ),
    ]
