# Generated by Django 4.2 on 2023-10-29 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_transaction_rename_create_at_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
