# Generated by Django 4.2 on 2023-10-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.stripepayment'),
        ),
    ]
