# Generated by Django 4.2 on 2023-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_payment_stripe_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
