# Generated by Django 4.2 on 2023-10-30 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Subscriber',
        ),
    ]
