# Generated by Django 4.2 on 2023-11-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
