# Generated by Django 4.2 on 2023-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('items', models.JSONField()),
                ('customer', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'completed')], default=0)),
                ('payment_method', models.IntegerField(choices=[(1, 'strip'), (2, 'paypal')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
