# Generated by Django 4.2 on 2023-11-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('courses', '0023_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
